### ISSUE TITLE
Smooth Scroll Link triggers Page Transition

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-page-transition-plugin-changelog#1]
Hi

How can I use the Smooth Scroll Component without triggering a Page Transition Animation on click?
 
https://manuelvonrotz.ch/page-transition-scroll-test/

**Comment by claudia-romano** [comment]
Hi there, only the links with a `.js-page-trans-link` class triggers a page transition animation. You can find more info here:
https://codyhouse.co/ds/components/info/page-transition-plugin

Cheers!

**Comment by matobeag** [comment]
yeah i know, but the link in my example does not have a `.js-page-trans-link` class
`<a class="btn btn--primary js-smooth-scroll" href="#section-2">Scroll down</a>`

**Comment by claudia-romano** [comment]
Thanks for heads-up. There was an issue with hash links. 

We just pushed an updated version fixing the bug. You can get the update code here:
https://codyhouse.co/ds/components/app/page-transition-plugin

Cheers!
